patch juju-backup to work with the local provider

diff --git a/cmd/plugins/juju-backup/juju-backup b/cmd/plugins/juju-backup/juju-backup
--- a/cmd/plugins/juju-backup/juju-backup
+++ b/cmd/plugins/juju-backup/juju-backup
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 remote_cmd() {	
-	LIBJUJU=/var/lib/juju
+        #USER=ubuntu
+        USER=jameinel
+	#LIBJUJU=/var/lib/juju
+	LIBJUJU=/home/$USER/.juju/local
 
 	# usage: execute message cmd [arg...]
 	# Execute the given command with the given arguments and exit with an
@@ -55,15 +58,15 @@ remote_cmd() {
 
 	#---------------------------------------------------------------------
 	next_step 'Backing up mongo database'
-	execute 'Stopping mongo' stop juju-db
-	trap "start juju-db" 0		# ensure it starts again on failure
+	execute 'Stopping mongo' stop juju-db-$USER-local
+	trap "start juju-db-$USER-local" 0		# ensure it starts again on failure
 	execute 'Backing up mongo' $MONGODUMP --dbpath $LIBJUJU/db
 	execute 'Backing up environ config' $MONGOEXPORT \
 		--dbpath $LIBJUJU/db \
 		--db juju \
 		--collection settings \
 		--out environconfig.json
-	execute 'Starting mongo' start juju-db
+	execute 'Starting mongo' start juju-db-$USER-local
 	trap - 0
 
 	next_step 'Copying Juju configuration'
@@ -98,7 +101,8 @@ remote_cmd() {
 	cd ..
 	execute 'Performing tar' tar -czf juju-backup.tgz juju-backup
 	rm -r juju-backup
-	execute 'Changing ownership of backup archive to ubuntu' chown -R ubuntu.ubuntu juju-backup*
+	#execute 'Changing ownership of backup archive to ubuntu' chown -R ubuntu.ubuntu juju-backup*
+	execute 'Changing ownership of backup archive to ubuntu' chown -R $USER.$USER juju-backup*
 	
 	echo
 	echo Juju backup finished.
@@ -113,10 +117,10 @@ REMOTE_SCRIPT="
 
 QUOTED_SCRIPT="'$(echo "$REMOTE_SCRIPT" | sed "s/'/'\"'\"'/g")'"
 echo Connecting to machine 0
-juju ssh 0 "sudo -n bash -c $QUOTED_SCRIPT" && {
+ssh localhost -t "sudo bash -c $QUOTED_SCRIPT" && {
 	# The backup has succeeded; copy backup tarball locally.
 	NOW=$(date '+%Y%m%d-%H%M')
 	FILENAME=juju-backup-$NOW.tgz
 	echo "Copying tarball to `pwd`/$FILENAME ..."
-	juju scp 0:~/juju-backup.tgz ./$FILENAME
+	scp localhost:~/juju-backup.tgz ./$FILENAME
 }
